// Imports
import './globals.css';
import type { Metadata } from 'next';
import { LayoutPropsType } from '@/utils/types';
import Providers from '@/utils/Providers';
// MetaData
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
// Layout Component
const RootLayout = ( { children }: LayoutPropsType ) => {
    // Return JSX Elements
    return (
        <html lang="en">
            <body>
                <Providers>
                    { children }
                </Providers>
            </body>
        </html>
    )
}
// Exports
export default RootLayout;